//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANy
    {
        public short PFK_ENTERPRISE { get; set; }
        public short PK_COMPANY { get; set; }
        public string DES_COMPANY { get; set; }
        public string LEGAL_NAME { get; set; }
        public string BILL_NAME { get; set; }
        public string VAT_NUMBER1 { get; set; }
        public string VAT_NUMBER2 { get; set; }
        public short FK_COUNTRY { get; set; }
        public short FK_PROVINCES { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public string POSTAL_CODE { get; set; }
        public short FK_BILL_COUNTRY { get; set; }
        public short FK_BILL_PROVINCES { get; set; }
        public string BILL_CITY { get; set; }
        public string BILL_ADDRESS { get; set; }
        public string BILL_POSTAL_CODE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public short FK_CURRENCY { get; set; }
        public short FK_CURRENCY_REPORT { get; set; }
        public short FK_LANGUAGE { get; set; }
        public string ARTICLE_PREFIX { get; set; }
        public string SERVER_IP_ADDRESS { get; set; }
        public string SERVER_SERVICE_PORT { get; set; }
        public string SERVER_DOCUMENTS_DIR { get; set; }
        public string SERVER_DOCUMENTS_CACHE_DIR { get; set; }
        public string SERVER_SHIPMENTS_DIR { get; set; }
        public Nullable<short> INTERFACE_ACCOUNTING_MODEL { get; set; }
        public string LINKED_SERVER_NAME { get; set; }
        public Nullable<short> FK_CREATION_USER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<short> FK_LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public byte[] ts { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
