//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRy
    {
        public short PFK_ENTERPRISE { get; set; }
        public short PK_COUNTRY { get; set; }
        public string DES_COUNTRY { get; set; }
        public string ISO_CODE { get; set; }
        public string ISO_EXT_CODE { get; set; }
        public string CALL_CODE_PREFIX { get; set; }
        public Nullable<short> ISO3166_NUMBER { get; set; }
        public string ZIP_CODE_MASK { get; set; }
        public Nullable<bool> IS_MEMBER_OF_EEC { get; set; }
        public Nullable<short> FK_CREATION_USER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<short> FK_LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public byte[] ts { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<short> FK_STATUS { get; set; }
    }
}
