//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBS_CATEGORY_MATRIX
    {
        public string Cat_pk { get; set; }
        public string Category_name { get; set; }
        public string Sub_cat_pk { get; set; }
        public string Sub_Category_name { get; set; }
        public string SUB_SUB_Cat_PK { get; set; }
        public string SUB_sub_category_NAME { get; set; }
        public string MERCH_Main { get; set; }
        public string MERCH_Backup { get; set; }
        public Nullable<short> fk_company_bo { get; set; }
        public Nullable<short> FK_MERCH { get; set; }
        public Nullable<short> FK_sub_MERCH { get; set; }
        public Nullable<int> fk_Buying_team { get; set; }
        public string fk_Purchasing_category { get; set; }
        public string fk_Purchasing_Subcategory { get; set; }
        public Nullable<bool> IS_DEFAULT { get; set; }
        public Nullable<short> MERCH_COMP { get; set; }
        public Nullable<int> OLD_FK_purchasing_subcat { get; set; }
        public Nullable<int> OLD_FK_purchasing_cat { get; set; }
        public int GCMID { get; set; }
    }
}
