//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public short PFK_ENTERPRISE { get; set; }
        public short PFK_COMPANY { get; set; }
        public short PK_TEAM { get; set; }
        public string SHORT_TEAM { get; set; }
        public string DES_TEAM { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<short> FK_ACCOUNT_MANAGER { get; set; }
        public Nullable<short> FK_CREATION_USER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<short> FK_LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public byte[] ts { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
