//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.TEAMS = new HashSet<TEAM>();
        }
    
        public short PFK_ENTERPRISE { get; set; }
        public short PK_USER { get; set; }
        public short FK_COMPANY { get; set; }
        public short FK_DIVISION { get; set; }
        public string LOGIN { get; set; }
        public byte[] PASSWORD { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> CAN_SIGN_ORDER_CONFIRM { get; set; }
        public byte[] SIGN_ORDER_CONFIRM_PASSWORD { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<bool> IS_ENABLED { get; set; }
        public Nullable<bool> IS_SUPER_USER { get; set; }
        public Nullable<short> FK_USER_ACCESS_PROFILE { get; set; }
        public Nullable<bool> IS_NET_WAM_USER { get; set; }
        public Nullable<short> FK_NET_SECURITY_LEVEL { get; set; }
        public Nullable<bool> NET_FILES_ACCESS { get; set; }
        public Nullable<bool> NET_OLD_INTRANET_ACCESS { get; set; }
        public Nullable<bool> HAS_NEWS { get; set; }
        public Nullable<short> FK_CREATION_USER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<short> FK_LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public byte[] ts { get; set; }
        public System.Guid rowguid { get; set; }
        public string PASSWORD1 { get; set; }
        public string SIGN_ORDER_CONFIRM_PASSWORD_PFCTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM> TEAMS { get; set; }
    }
}
